# Generated by Django 3.1 on 2020-10-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='toal',
            new_name='total',
        ),
    ]
